plugins:
  - "@semantic-release/commit-analyzer"
  - "@semantic-release/release-notes-generator"
  - - "@semantic-release/exec"
    - prepareCmd: |
        yarn lerna version ${nextRelease.version} \
          --no-git-tag-version \
          --yes
      publishCmd: |
        echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> .npmrc
        npm whoami
        cd packages/parse-manifests && npm publish
  - - "@semantic-release/git"
    - assets:
        - CHANGELOG.md
        - lerna.json
        - package.json
        - packages/*/CHANGELOG.md
        - packages/*/package.json
      message: "chore(release): version ${nextRelease.version}\n\n${nextRelease.notes}"
  - "@semantic-release/github"
