name: ci
on:
  - push
  - pull_request

jobs:
  build:
    name: ubuntu-latest
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18.x
          cache: yarn

      - name: Install kubeseal for Ubuntu
        run: |
          wget https://github.com/bitnami-labs/sealed-secrets/releases/download/v0.12.6/kubeseal-linux-amd64 -O kubeseal
          #
          sudo install -m 755 kubeseal /usr/local/bin/kubeseal

      - name: Install
        run: yarn --frozen-lockfile --perfer-offline

      - name: Lint
        run: yarn lint

      - name: Build
        run: yarn build

      - name: Test
        run: yarn test

      - name: Test and coverage check
        run: yarn test-coverage

      - name: Send test coverage to codecov
        uses: codecov/codecov-action@v2
        continue-on-error: true

      - name: Generate sre-secrets artifacts
        uses: actions/upload-artifact@v2
        with:
          name: sre-secrets
          path: ./packages/sre-secrets/dist

  release:
    needs:
      - build
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: yarn

      - name: Install
        run: yarn --frozen-lockfile --perfer-offline

      - name: Npm Authenticate
        run: |
          echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> .npmrc
          npm whoami
        env:
          NPM_TOKEN: ${{ secrets.SOCIALGROOVYBOT_NPM_TOKEN }}

      - name: Download sre-secrets artifact
        uses: actions/download-artifact@v2
        with:
          name: sre-secrets
          path: ./packages/sre-secrets/dist

      - name: Semantic Release
        if: |
          github.event_name == 'push' &&
          github.repository == 'SocialGouv/sre-tools'
        uses: cycjimmy/semantic-release-action@v2
        id: semantic
        with:
          semantic_version: 19
          extra_plugins: |
            @semantic-release/exec
            @semantic-release/git
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GIT_AUTHOR_EMAIL: ${{ secrets.SOCIALGROOVYBOT_EMAIL }}
          GIT_AUTHOR_NAME: ${{ secrets.SOCIALGROOVYBOT_NAME }}
          GIT_COMMITTER_EMAIL: ${{ secrets.SOCIALGROOVYBOT_EMAIL }}
          GIT_COMMITTER_NAME: ${{ secrets.SOCIALGROOVYBOT_NAME }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.SOCIALGROOVYBOT_NPM_TOKEN }}

      - name: New version
        if: steps.semantic.outputs.new_release_published == 'true'
        run: |
          echo ${{ steps.semantic.outputs.new_release_version }}
