name: webseal publish

on:
  push:
    branches: [master]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: yarn

      - name: Build
        run: |
          cd packages/webseal
          yarn
          yarn build

      - name: GH Pages deploy
        uses: Cecilapp/GitHub-Pages-deploy@3.2.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          email: ${{ secrets.SOCIALGROOVYBOT_EMAIL }}
          build_dir: packages/webseal/build
          branch: gh-pages
